
macro(SET_COMMON_COMPILER_FLAGS)
  list(JOIN EUSTIA_COMPILER_FLAGS " " CMAKE_CXX_FLAGS)
  list(JOIN EUSTIA_COMPILER_FLAGS_DEBUG " " CMAKE_CXX_FLAGS_DEBUG)
  list(JOIN EUSTIA_COMPILER_FLAGS_RELEASE " " CMAKE_CXX_FLAGS_RELEASE)
endmacro()

macro(SET_COMMON_EXE_LINKER_FLAGS)
  list(JOIN EUSTIA_LINKER_FLAGS " " CMAKE_EXE_LINKER_FLAGS)
  list(JOIN EUSTIA_LINKER_FLAGS_DEBUG " " CMAKE_EXE_LINKER_FLAGS_DEBUG)
  list(JOIN EUSTIA_LINKER_FLAGS_RELEASE " " CMAKE_EXE_LINKER_FLAGS_RELEASE)
endmacro()

macro(SET_COMMON_SHARED_LINKER_FLAGS)
  list(JOIN EUSTIA_LINKER_FLAGS " " CMAKE_SHARED_LINKER_FLAGS)
  list(JOIN EUSTIA_LINKER_FLAGS_DEBUG " " CMAKE_SHARED_LINKER_FLAGS_DEBUG)
  list(JOIN EUSTIA_LINKER_FLAGS_RELEASE " " CMAKE_SHARED_LINKER_FLAGS_RELEASE)
endmacro()