
macro(SET_COMMON_COMPILER_FLAGS)
  list(JOIN EUSTIA_COMPILER_FLAGS " " CMAKE_CXX_FLAGS)
  list(JOIN EUSTIA_COMPILER_FLAGS_DEBUG " " CMAKE_CXX_FLAGS_DEBUG)
  list(JOIN EUSTIA_COMPILER_FLAGS_RELEASE " " CMAKE_CXX_FLAGS_RELEASE)
endmacro()